spring:
  application:
    name: backend

  config:
    import: optional:classpath:properties/env.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

github:
  oauth:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
    authorize-uri: https://github.com/login/oauth/authorize
    token-uri: https://github.com/login/oauth/access_token
    user-info-uri: https://api.github.com/user
    user-email-uri: https://api.github.com/user/emails
    redirect-uri: http://localhost:8080/api/v1/oauth/callback
    scope: read:user user:email

jwt:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-access-token-lifetime: ${JWT_ACCESS_TOKEN_LIFETIME}
  jwt-refresh-token-lifetime: ${JWT_REFRESH_TOKEN_LIFETIME}
