spring:
  application:
    name: backend

  config:
    import: optional:classpath:properties/env.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

github:
  oauth:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
    authorize-uri: https://github.com/login/oauth/authorize
    token-uri: https://github.com/login/oauth/access_token
    user-info-uri: https://api.github.com/user
    user-email-uri: https://api.github.com/user/emails
    redirect-uri: https://issue-tracker.o-r.kr/api/v1/oauth/callback
    scope: read:user user:email

jwt:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-access-token-lifetime: ${JWT_ACCESS_TOKEN_LIFETIME}
  jwt-refresh-token-lifetime: ${JWT_REFRESH_TOKEN_LIFETIME}

image:
  upload:
    allowed-extensions: jpg,jpeg,png,gif,webp
    max-size: 10485760  # 10MB in bytes
    base-url: https://${AWS_S3_BUCKET_NAME}.s3.${AWS_REGION:ap-northeast-2}.amazonaws.com
